<?php
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $helper \MagoArab\OrderActions\Helper\Data
 */
$helper = $this->helper('MagoArab\OrderActions\Helper\Data');
$roleId = $helper->getCurrentUserRoleId();
?>
<?php if ($helper->isEnabled()): ?>
<script type="text/x-magento-init">
{
    "*": {
        "MagoArab_OrderActions/js/dynamic-menu-filter": {
            "isEnabled": <?= $helper->isEnabled() ? 'true' : 'false' ?>,
            "permissions": <?= json_encode($helper->getOrderActionsWithPermissions($roleId)) ?>
        }
    }
}
</script>
<?php endif; ?>