<?php
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $helper \MagoArab\OrderActions\Helper\Data
 */
$helper = $this->helper('MagoArab\OrderActions\Helper\Data');
?>
<?php if ($helper->isEnabled()): ?>
<script type="text/x-magento-init">
{
    "*": {
        "MagoArab_OrderActions/js/dynamic-resource-manager": {
            "collectUrl": "<?= $block->getUrl('magoarab_orderactions/ajax/collectActions') ?>",
            "formKey": "<?= $block->getFormKey() ?>",
            "isEnabled": <?= $helper->isEnabled() ? 'true' : 'false' ?>
        }
    }
}
</script>
<?php endif; ?>